MOSAIC:
  mosaic_th : 0.5
  translate : 0.1
  scale : 0.5 # +-
  rotation : 45

COPY_PASTE:
  copy_paste_scale : 0.5
  copy_paste_rotation : 45
  copy_paste_th : 0.5

RANDOM_ERASE:
  random_erase_th : 0.5