MOSAIC:
  mosaic_th : 1
  translate : 0.1
  scale : [0.1, 1.9]  #0.1, 1.0    0.5 1.5
  rotation : 0

RANDOM_ERASE:
  random_erase_th : 0.5

COPY_PASTE:
  copy_paste_scale : [0.5, 1.0]
  copy_paste_rotation : 180
  copy_paste_th : 0.5