MOSAIC:
  mosaic_th : 0.522
  translate : 0.39
  scale : 0.3485 # +-
  rotation : 14

COPY_PASTE:
  copy_paste_scale : 0.8183
  copy_paste_rotation : 158
  copy_paste_th : 1.0

RANDOM_ERASE:
  random_erase_th : 0.531