MISC:
  PRE_PROCESS: "default"  # "default" or "paper"
  PCD_CONFIG : "full" # "crop" or "full"
  PCD_FRACTION : 0.75
  MAX_EPOCHS : 1000
  NUM_WORKERS : 8
  BATCH_SIZE : 5
  NUM_SETS : 5

HPARAMS:
  encoder_arch : 'resnet18'
  local_kernel_size : 3
  stride : 1
  padding : 1
  groups : 4
  drtam : False
  refinement : False