MISC:
  PRE_PROCESS: "default"  # "default" or "paper"
  PCD_CONFIG : "crop" # "crop" or "full"
  MAX_EPOCHS : 150
  NUM_WORKERS : 8
  BATCH_SIZE : 16
  NUM_SETS : 5

HPARAMS:
  encoder_arch : 'resnet18'
  local_kernel_size : 1
  stride : 1
  padding : 0
  groups : 4
  drtam : False
  refinement : False