MISC:
  PRE_PROCESS: "-"  # "default" or "paper"
  PCD_CONFIG : "-" # "crop" or "full"
  MAX_EPOCHS : 150
  NUM_WORKERS : 12
  BATCH_SIZE : 1
  NUM_SETS : 1

HPARAMS:
  encoder_arch : 'resnet18'
  local_kernel_size : 1
  stride : 1
  padding : 0
  groups : 4
  drtam : False
  refinement : False