MISC:
  PRE_PROCESS: "-"  # "default" or "paper"
  PCD_CONFIG : "-" # "crop" or "full"
  MAX_EPOCHS : 150
  NUM_WORKERS : 8
  BATCH_SIZE : 6
  NUM_SETS : 1

HPARAMS:
  encoder_arch : 'resnet18'
  local_kernel_size : 3
  stride : 1
  padding : 1
  groups : 4
  drtam : True
  refinement : False