MISC:
  PRE_PROCESS: "paper"  # "default" or "paper"
  PCD_CONFIG : "crop" # "crop" or "full"
  MAX_EPOCHS : 150
  NUM_WORKERS : 8
  BATCH_SIZE : 16
  NUM_SETS : 5
  LOG_NAME : "paper_configuration_ALL_AUGMENTATIONS"
  AUGMENT_ON : True

HPARAMS:

  encoder_arch : 'resnet18'
  local_kernel_size : 1
  stride : 1
  padding : 0
  groups : 4
  drtam : False
  refinement : False

AUGMENTATIONS:

  MOSAIC:
    mosaic_on : True
    mosaic_th : 1.0
    translate : 0.1
    scale : [0.1, 1.0]
    rotation : 45

  RANDOM_ERASE:
    random_erase_on : True
    random_erase_th : 0.7

  ALBUMENTATIONS:
    albumentations_on : True
  
  COPY_PASTE:
    copy_paste_on : True
    copy_paste_scale : [0.3, 1.0]
    copy_paste_rotation : 180
    copy_paste_th : 0.5
